server:
  port: 8181
spring:
  application:
    name: springcloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.190.31:8848
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
    gateway:
      routes:
        ### 路由的ID,没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
        ### 匹配后提供的路由地址
          uri: lb://springcloud-payment
          ### 断言，路径匹配的进行路由
          predicates:
            - Path=/payment/**
        - id: stock_routh
          uri: lb://springcloud-stock
          predicates:
            - Path=/stock/**
        - id: login_routh
          uri: lb://springcloud-login
          predicates:
            - Path=/login
  r2dbc:
    username: root
    password: 123456
    url: r2dbcs:mysql://localhost:3306/test