spring:
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.190.31:8848
      config:
        server-addr: 114.132.190.31:8848
        file-extension: yml
        prefix: ${spring.application.name}
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'